
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter import filedialog

def browse_video_file():
    file_path = filedialog.askopenfilename(filetypes=[("Video files", "*.mp4;*.avi"), ("All files", "*.*")])
    
    print("Selected video file:", file_path)

def browse_location_file():
    file_path = filedialog.askopenfilename(filetypes=[("JSON files", "*.json")])
    
    print("Selected location file:", file_path)


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/yakuptokmakci/Desktop/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("650x400")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 400,
    width = 650,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    325.0,
    200.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda:browse_location_file() ,
    relief="flat"
)
button_1.place(
    x=8.0,
    y=170.0,
    width=155.0,
    height=30.0
)

canvas.create_text(
    165.0,
    23.0,
    anchor="nw",
    text="Collapse Building Analysis",
    fill="#FFFFFF",
    font=("Inter BlackItalic", 24 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=8.0,
    y=331.0,
    width=100.0,
    height=30.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=165.0,
    y=331.0,
    width=100.0,
    height=30.0
)

canvas.create_text(
    463.0,
    116.0,
    anchor="nw",
    text="Results",
    fill="#FFFFFF",
    font=("Inter BlackItalic", 12 * -1)
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda:browse_video_file(),
    relief="flat"
)
button_4.place(
    x=8.0,
    y=110.0,
    width=154.52996826171875,
    height=30.0
)
window.resizable(False, False)
window.mainloop()
